/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeDashboard;

import java.awt.Dimension;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import vrs.loginForm;
import vrs.rentals;
import config.Logger;


/**
 *
 * @author ROCO
 */
public class employeeDashBoard extends javax.swing.JFrame {

    private String currentUsername;
    private String currentUser;
    
     
    
    /**
     * Creates new form employeeDashBoard
     */
    public employeeDashBoard() {
        initComponents();
        try {
            // Log dashboard initialization
            Logger.log("INIT", "Employee dashboard initialized", currentUsername, "127.0.0.1");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void setUsername(String username) {
        try {
            this.currentUsername = username;
            
            // Log username set
            Logger.log("INFO", "Employee username set: " + username, username, "127.0.0.1");
            
            // Format the welcome message to fit
            if (username.length() > 8) {
                // If username is too long, use multiple lines
                
                // Use a panel with BoxLayout for multiple lines
                JPanel textPanel = new JPanel();
                textPanel.setLayout(new javax.swing.BoxLayout(textPanel, javax.swing.BoxLayout.Y_AXIS));
                textPanel.setOpaque(false); // Make it transparent
                
                // First line is "WELCOME"
                JLabel welcomeLabel = new JLabel("WELCOME");
                welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
                welcomeLabel.setForeground(java.awt.Color.WHITE);
                welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                welcomeLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
                
                // Second line is the username
                JLabel usernameLabel = new JLabel(username);
                usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 12));
                usernameLabel.setForeground(java.awt.Color.WHITE);
                usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                usernameLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
                
                textPanel.add(welcomeLabel);
                textPanel.add(usernameLabel);
                
                // Clear and set panel
                welcomePanel.removeAll();
                welcomePanel.setLayout(new java.awt.BorderLayout());
                welcomePanel.add(textPanel, java.awt.BorderLayout.CENTER);
            } else {
                // If username is short enough, use two lines
                JPanel textPanel = new JPanel();
                textPanel.setLayout(new javax.swing.BoxLayout(textPanel, javax.swing.BoxLayout.Y_AXIS));
                textPanel.setOpaque(false); // Make it transparent
                
                // First line
                JLabel welcomeLabel = new JLabel("WELCOME");
                welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
                welcomeLabel.setForeground(java.awt.Color.WHITE);
                welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                welcomeLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
                
                // Second line
                JLabel usernameLabel = new JLabel(username);
                usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
                usernameLabel.setForeground(java.awt.Color.WHITE);
                usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                usernameLabel.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
                
                textPanel.add(welcomeLabel);
                textPanel.add(usernameLabel);
                
                // Clear and set panel
                welcomePanel.removeAll();
                welcomePanel.setLayout(new java.awt.BorderLayout());
                welcomePanel.add(textPanel, java.awt.BorderLayout.CENTER);
            }
            
            welcomePanel.revalidate();
            welcomePanel.repaint();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setCurrentUser(String username) {
    this.currentUser = username;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        e_dash = new javax.swing.JButton();
        e_client = new javax.swing.JButton();
        view_vehicles = new javax.swing.JButton();
        welcomePanel = new javax.swing.JPanel();
        mainD = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1085, 721));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1085, 721));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("EMPLOYEE PANEL");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 0, 504, 100));

        logout.setText("LOGOUT");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel3.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 120, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        e_dash.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        e_dash.setText("DASHBOARD");
        e_dash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_dashActionPerformed(evt);
            }
        });

        e_client.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        e_client.setText("ADD CLIENTS");
        e_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_clientActionPerformed(evt);
            }
        });

        view_vehicles.setFont(new java.awt.Font("Microsoft YaHei", 3, 12)); // NOI18N
        view_vehicles.setText("VIEW VEHICLES");
        view_vehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_vehiclesActionPerformed(evt);
            }
        });

        welcomePanel.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(view_vehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e_dash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(e_client, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(welcomePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(welcomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(e_dash, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(e_client, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(view_vehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 640));

        mainD.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainDLayout = new javax.swing.GroupLayout(mainD);
        mainD.setLayout(mainDLayout);
        mainDLayout.setHorizontalGroup(
            mainDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        mainDLayout.setVerticalGroup(
            mainDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(mainD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 910, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e_dashActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Log dashboard access
            Logger.log("ACCESS", "Employee accessed dashboard", currentUsername, "127.0.0.1");
            
            mainD.removeAll();
            rentals rentalsPanel = new rentals();
            mainD.add(rentalsPanel);
            rentalsPanel.setVisible(true);
            mainD.revalidate();
            mainD.repaint();
            
            // Log successful panel display
            Logger.log("INFO", "Dashboard panel displayed successfully", currentUsername, "127.0.0.1");
        } catch (Exception e) {
            // Log error
            Logger.log("ERROR", "Failed to display dashboard: " + e.getMessage(), currentUsername, "127.0.0.1");
            e.printStackTrace();
        }
    }

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            // Log the logout action
            Logger.log("LOGOUT", "Employee logged out", currentUsername, "127.0.0.1");
            
            // Open login form and close current window
            loginForm log = new loginForm();
            log.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void view_vehiclesActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Log vehicles view access
            Logger.log("ACCESS", "Employee accessed vehicles view", currentUsername, "127.0.0.1");
            
            for (java.awt.Component comp : mainD.getComponents()) {
                if (comp instanceof vrs.v_vehicles) {
                    // Log existing panel access
                    Logger.log("INFO", "Accessed existing vehicles panel", currentUsername, "127.0.0.1");
                    comp.setVisible(true);
                    try {
                        ((javax.swing.JInternalFrame) comp).setSelected(true);
                    } catch (java.beans.PropertyVetoException e) {
                        Logger.log("ERROR", "Failed to select vehicles panel: " + e.getMessage(), currentUsername, "127.0.0.1");
                        e.printStackTrace();
                    }
                    return;
                }
            }
            
            // Create and open new v_vehicles
            vrs.v_vehicles vehicles = new vrs.v_vehicles();
            mainD.add(vehicles);
            vehicles.setVisible(true);
            try {
                vehicles.setMaximum(true);
                vehicles.setSelected(true);
                // Log successful panel creation
                Logger.log("INFO", "New vehicles panel created and displayed", currentUsername, "127.0.0.1");
            } catch (java.beans.PropertyVetoException e) {
                Logger.log("ERROR", "Failed to maximize vehicles panel: " + e.getMessage(), currentUsername, "127.0.0.1");
                e.printStackTrace();
            }
        } catch (Exception e) {
            Logger.log("ERROR", "Failed to access vehicles view: " + e.getMessage(), currentUsername, "127.0.0.1");
            e.printStackTrace();
        }
    }

    private void e_clientActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Log clients view access
            Logger.log("ACCESS", "Employee accessed clients management", currentUsername, "127.0.0.1");
            
            for (java.awt.Component comp : mainD.getComponents()) {
                if (comp instanceof vrs.add_clients) {
                    // Log existing panel access
                    Logger.log("INFO", "Accessed existing clients panel", currentUsername, "127.0.0.1");
                    comp.setVisible(true);
                    try {
                        ((javax.swing.JInternalFrame) comp).setSelected(true);
                    } catch (java.beans.PropertyVetoException e) {
                        Logger.log("ERROR", "Failed to select clients panel: " + e.getMessage(), currentUsername, "127.0.0.1");
                        e.printStackTrace();
                    }
                    return;
                }
            }
            
            // Create and open new add_clients
            vrs.add_clients clients = new vrs.add_clients();
            mainD.add(clients);
            clients.setVisible(true);
            try {
                clients.setMaximum(true);
                clients.setSelected(true);
                // Log successful panel creation
                Logger.log("INFO", "New clients panel created and displayed", currentUsername, "127.0.0.1");
            } catch (java.beans.PropertyVetoException e) {
                Logger.log("ERROR", "Failed to maximize clients panel: " + e.getMessage(), currentUsername, "127.0.0.1");
                e.printStackTrace();
            }
        } catch (Exception e) {
            Logger.log("ERROR", "Failed to access clients management: " + e.getMessage(), currentUsername, "127.0.0.1");
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employeeDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employeeDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employeeDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employeeDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employeeDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton e_client;
    private javax.swing.JButton e_dash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout;
    private javax.swing.JDesktopPane mainD;
    private javax.swing.JButton view_vehicles;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
